### ISSUE TITLE
image-type: Invalid image type ‘imagemagick’

### ISSUE THREAD

**Issue by sergey-pashaev** [larsmagne/meme#2]
Tried `M-x meme` in `emacs -Q` after installation:

```
(setq load-path (cons (expand-file-name "~/src/meme") load-path))
(autoload 'meme "meme.el" "Create a meme from a collection" t)
(autoload 'meme-file "meme.el" "Create a meme from a file" t)
```

I've got error:
`eval-buffer: Cannot open load file: No such file or directory, svg`

I've installed and loaded svg package by hand. Tried `M-x meme` once again and got another error:
`image-type: Invalid image type ‘imagemagick’`

Emacs version: GNU Emacs 25.0.95.1 (i686-pc-linux-gnu, GTK+ Version 2.24.10) of 2016-06-24

**Comment by larsmagne** [comment]
I should have specified in the readme that you need the very latest master Emacs from git, built with all the standard goodies (including imagemagick).
