### ISSUE TITLE
Output image's font is not same as emacs preview

### ISSUE THREAD

**Issue by vuquangtam** [larsmagne/meme#6]
I'm using emacs 27.1 and using lastest version of meme package
This is output file
![output](https://user-images.githubusercontent.com/6467819/101595942-cdbfcf00-3a26-11eb-98d7-30517b947f15.png)

This is emacs preview
![emacs preview](https://user-images.githubusercontent.com/6467819/101595969-da442780-3a26-11eb-9795-4009595333be.png)

**Comment by larsmagne** [comment]
Looks like Emacs and Imagemagick convert interprets stroke-width differently?  I've now tweaked it, and it seems to work for me again now.

**Comment by vuquangtam** [comment]
I pulled latest version but it doesn't work. Maybe it relates to imagemagick doesn't compile in emacs 27.1?
https://devclass.com/2020/08/11/dont-look-vi-users-emacs-27-1-waves-bye-to-imagemagick-adds-native-json-parsing-support/

**Comment by larsmagne** [comment]
What does the resulting image look like now?  I suspect some versions of ImageMagick convert interprets SVGs differently than others.  The current meme.el version works with the ImageMagick convert version on Debian/bullseye.

**Comment by vuquangtam** [comment]
> What does the resulting image look like now? I suspect some versions of ImageMagick convert interprets SVGs differently than others. The current meme.el version works with the ImageMagick convert version on Debian/bullseye.

Hi, i pulled the latest version and it works fine, thank you.
